version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: generalii-improved
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - generalii-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  generalii-network:
    driver: bridge

